### PR TITLE
Adapt new magic codes for Python 3.10a3

### PR DESCRIPTION
**Pull request by frenzymadness**

### CODE REVIEW

**Comment by hroncok** [comment]
Here's a Fedora 33 scratchbuild of the new alpha in case you want to test it locally: https://koji.fedoraproject.org/koji/taskinfo?taskID=57037360

**Comment by hroncok** [comment]
I've run the tox tests without this PR with the old alpha and it works, because the test data is in this repo.

**Comment by hroncok** [comment]
However, this PR works:

```
[marshalparser (master %)]$ python -m marshalparser /usr/lib64/python3.10/__pycache__/cmd.cpython-310.pyc 
Cannot read/parse byte 104 b'h' on possition 0
Might be error or unsupported TYPE

[marshalparser (master %)]$ git pull origin refs/pull/14/head
From github.com:fedora-python/marshalparser
 * branch            refs/pull/14/head -> FETCH_HEAD
Updating a545717..5c0f399
Fast-forward
 marshalparser/magic.py | 2 ++
 1 file changed, 2 insertions(+)
[marshalparser (master %)]$ python -m marshalparser /usr/lib64/python3.10/__pycache__/cmd.cpython-310.pyc 
[marshalparser (master %)]$ echo $?
0
```

**Comment by frenzymadness** [comment]
I did the same test with locally compiled Python 3.10a2+. It might make sense to add some new testing files but I did it so far only from Fedora RPM. I'll add some from the scratch build of yours.

**Comment by hroncok** [comment]
One part of the problem I don't understand. To support the new bytecode magic number, doesn't some marhsalparser code need to be adapted as well?

**Comment by frenzymadness** [comment]
> One part of the problem I don't understand. To support the new bytecode magic number, doesn't some marhsalparser code need to be adapted as well?

Magic numbers are used for the detection of Python version so we have to adapt the latest one to stay compatible. But if the content - in the matter of compiled data types and their structure - stays the same, we don't have to change anything else.

For example [the latest change](https://github.com/python/cpython/commit/7301979b23406220510dd2c7934a21b41b647119) changes how annotations are stored internally (from slow dict to fast tuple) but marshalparser can parse both so we don't have to change anything here.

**Comment by hroncok** [comment]
Got it, thanks!

Some newly added files are empty. Is that intentional?

**Comment by frenzymadness** [comment]
> Got it, thanks!
> 
> Some newly added files are empty. Is that intentional?

It's not, thanks for spotting it. It means that they are empty also in the RPM package. I'll fix them.

**Comment by hroncok** [comment]
> It means that they are empty also in the RPM package.

```
[marshalparser (master %)]$ du -h test/python_stdlib/3.10/pydoc_mod.cpython-310.opt-1.pyc
0	test/python_stdlib/3.10/pydoc_mod.cpython-310.opt-1.pyc
[marshalparser (master %)]$ du -h /usr/lib64/python3.10/test/__pycache__/pydoc_mod.cpython-310.opt-1.pyc
4,0K	/usr/lib64/python3.10/test/__pycache__/pydoc_mod.cpython-310.opt-1.pyc
```

**Comment by frenzymadness** [comment]
> > It means that they are empty also in the RPM package.
> 
> ```
> [marshalparser (master %)]$ du -h test/python_stdlib/3.10/pydoc_mod.cpython-310.opt-1.pyc
> 0	test/python_stdlib/3.10/pydoc_mod.cpython-310.opt-1.pyc
> [marshalparser (master %)]$ du -h /usr/lib64/python3.10/test/__pycache__/pydoc_mod.cpython-310.opt-1.pyc
> 4,0K	/usr/lib64/python3.10/test/__pycache__/pydoc_mod.cpython-310.opt-1.pyc
> ```

I've unpacked the RPM by archive manager and the file is empty on my disk, strange.

**Comment by hroncok** [comment]
> I've unpacked the RPM by archive manager and the file is empty on my disk, strange.

It might have to do something with hardlinks.

**Review by hroncok — APPROVED** [review]
If the CI passes, ship it.

**Pull request merged**
