### PR TITLE
Adapt to the new magic number

### PR DESCRIPTION
**Pull request by frenzymadness**
https://github.com/python/cpython/commit/bf353f3c2d937772a8cf30b15fd8eb7b82665ccb

### CODE REVIEW

**Comment by hroncok** [comment]
Side question: Have you figured out how to watch the changes?

**Comment by hroncok** [comment]
Side proposal: What if, when the magic number is bigger than any known number, marshalparser would assume the latest known version (possibly with a warning)?

**Comment by frenzymadness** [comment]
> Side question: Have you figured out how to watch the changes?

Yes. Each "history" page on Github can work as an Atom feed. So, if you open any list of commits for a file or folder and add ".atom" to the URL, you get a feed. Then, you can use a regular reader or some service that sends you a digest from feeds.

> Side proposal: What if, when the magic number is bigger than any known number, marshalparser would assume the latest known version (possibly with a warning)?

Yes, I'm thinking about how to do it better. I considered having a range for every Python version and compare it just like an interval. The problem is that pure marshal data might contain whatever combination of bytes making it possible that even non-pyc files might be identified as pyc files and then the parsing would fail.

The magic numbers are incremented by 1 so what about adding some more for the future changes in Python bytecode before we come up with a better solution? I'll still follow the development closely so I'll be able to proactively react to any incompatible or anticipated change.

**Review by hroncok — APPROVED** [review]

**Comment by hroncok** [comment]
> The magic numbers are incremented by 1 so what about adding some more for the future changes in Python bytecode before we come up with a better solution?

That works as well.

**Review by hroncok — APPROVED** [review]
Looking great!

A small suggestion: Add a comment to the last known one explaining that the latter ones are "guess"?

**Pull request merged**
