### PR TITLE
Python 3.14 and related changes

### PR DESCRIPTION
**Pull request by frenzymadness**
Tested locally via tox with python3.14-3.14.0~a1-2.fc40

### CODE REVIEW

**Comment by hroncok** [comment]
The pytest-xdist dependency will cause trouble in ELN/RHEL.

It's OK if you plan to sed/patch it out in Fedora.

But perhaps running `tox -p` locally will yield a significant-enough speedup?

**Comment by frenzymadness** [comment]
Okay, I'll drop `pytest-xdist`. I've aimed more at speedup for a single environment as the number of tests is growing with each release of Python  But I can do it manually outside of the tox next time.

**Comment by frenzymadness** [comment]
Let's try it once more.

**Comment by frenzymadness** [comment]
The CI looks good now.

**Pull request merged**
