### PR TITLE
Don't use system byteorder anymore

### PR DESCRIPTION
**Pull request by frenzymadness**

### CODE REVIEW

**Comment by frenzymadness** [comment]
Manually tested on RHEL 8 s390x machine and built in Koji on the same: https://koji.fedoraproject.org/koji/taskinfo?taskID=51486822

**Review by hroncok — APPROVED** [review]
The build in Koji passed and I also see no remaining `byteorder` usage or `struct.unpack` calls. Thanks.

**Comment by frenzymadness** [comment]
Do we want to wait to test this update with the new multiarch fedora-python-tox?

**Comment by hroncok** [comment]
> Do we want to wait to test this update with the new multiarch fedora-python-tox?

IMHO nope. We tested manually in Koji. We should add s390x CI, but it does not need to block this.

**Comment by frenzymadness** [comment]
Thank you!

**Pull request merged**
